.PHONY: rwalk rnumbers diffusion gases 

RW=./rwalk.py
RN=./rnumbers.py
DI=./diffusion.py
GA=./gases.py
PART ?=

rwalk:
	$(RW) --part=1,2
rnumbers:
	$(RN) --part=1,2
diffusion:
	$(DI) 
gases:
	$(GA) --part=1,2,3 
